- hosts: all
  user: ubuntu
  become: yes
  connection: ssh
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
    - name: "Install ansible python3 mysql dependency"
      apt:
        name: python3-mysqldb
        state: latest

          # Install the needed package of mysql
    - name: Install MySQL packages
      apt: pkg={{ item }} state=present
      with_items:
        - bundler
        - mysql-server
        - mysql-client
        - libmysqlclient-dev
        - python-mysqldb
        - build-essential
      # Add PGP key to install mysql 5.7 from mysql repository
    - name: Add PGP key to install mysql 5.7 from mysql repository
      apt_key:
        keyserver: hkp://pgp.mit.edu:80
        id: 5072E1F5

    - name: Add official APT repository
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/debian/ stretch mysql-5.7"

    # Install mysql
    - name: Install mysql-server 5.7 
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - mysql-server

    # Mysql setup
    - name: Ensure anonymous users are not in the database
      mysql_user: name='' host=localhost state=absent

    - name: Remove test database
      mysql_db: name=test state=absent

    - name: Create root user root password 
      mysql_user:
        name: "root"
        password: "UzA9WHsmVMm"
        priv: "*.*:ALL,GRANT"
        append_privs: yes
        state: present
      no_log: True

    - name: create a new database 
      mysql_db: name=mcba_qa state=present login_user=root login_password=UzA9WHsmVMm

    - name: Creating int mysql user
      mysql_user:
        login_password: "UzA9WHsmVMm"  #mysql root password here
        name: "int_user"
        password: "zA9WHsmVMm321"
        priv:  mcba_qa.*:ALL
        host: "localhost"

    
    - name: Creating mysql  ext user 
      mysql_user: 
        login_password: "UzA9WHsmVMm"  #mysql root password here
        name: "ext_user"
        password: "extUzA9WHsmVMm" 
        priv:  mcba_qa.*:ALL
        host: "%"

    - name: copying mysqld.cnf file to server mysql.cnf
      copy:
        src: mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
   
        
