- hosts: all
  user: ubuntu
  become: yes
  connection: ssh
  tasks:

    - name: "Install ansible python3 mysql dependency"
      apt:
        name: python3-mysqldb
        state: latest

          # Install the needed package of mysql
    - name: Install MySQL packages
      apt: pkg={{ item }} state=present
      with_items:
        - bundler
        - mysql-server
        - mysql-client
        - libmysqlclient-dev
        - python-mysqldb
        - build-essential
      # Add PGP key to install mysql 5.7 from mysql repository
    - name: Add PGP key
      apt_key:
        keyserver: hkp://pgp.mit.edu:80
        id: 5072E1F5

    - name: Add official APT repository
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/debian/ stretch mysql-5.7"

    # Install mysql
    - name: Install mysql-server
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - mysql-server

    # Mysql setup
    - name: Ensure anonymous users are not in the database
      mysql_user: name='' host=localhost state=absent

    - name: Remove test database
      mysql_db: name=test state=absent

    - name: Create admin user
      mysql_user:
        name: "root"
        password: "password"
        priv: "*.*:ALL,GRANT"
        append_privs: yes
        state: present
      no_log: True

    - name: create a new database 
      mysql_db: name=db_name state=present login_user=root login_password=password
    
    - name: Create mysql user
      mysql_user: 
        login_password: "password"  #mysql rool password here
        name: "username"
        password: "newuserpassword" 
        priv:  dbname.*:ALL
        host: "%"
